//分类
let classify = [
  {
    "title":'热门推荐',
    "list":{
      //顶部图片
      "show_img":'hot.png',
      //下面的内容
      "content_list":[
        {
          "c_img":'m_category_hot_Lover.png',
          "c_text":'送恋人鲜花',
        },
        {
          "c_img":'m_category_hot_Elder.png',
          "c_text":'送长辈鲜花',
        },
        {
          "c_img":'m_category_hot_Birthday.png',
          "c_text":'生日鲜花',
        },
        {
          "c_img":'m_category_hot_Boxedflowers.png',
          "c_text":'礼盒鲜花',
        },
        {
          "c_img":'m_category_ppf_sort_Box.png',
          "c_text":'永生花',
        },
        {
          "c_img":'m_category_hot_Cake.png',
          "c_text":'蛋糕',
        },
        {
          "c_img":'m_category_hot_Cake_ganso.png',
          "c_text":'元祖蛋糕',
        },
        {
          "c_img":'m_category_hot_Goldfoilflower.png',
          "c_text":'金箔花',
        },
        {
          "c_img":'m_category_hot_Jewelry.png',
          "c_text":'首饰',
        },
        {
          "c_img":'m_category_hot_Chocolate_qiaoluo.png',
          "c_text":'巧罗巧克力',
        },
        {
          "c_img":'m_category_hot_CreativeGifts.png',
          "c_text":'创意礼品',
        },
        {
          "c_img":'m_category_hot_Groupbuy.png',
          "c_text":'企业团购',
        }
      ]
    }
  },
  {
    "title":'鲜花',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'对象',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'全部',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送女友鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送男性鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送长辈鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送朋友鲜花',
            }
          ]
        },
        {
          "c_tit":'场合',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
        {
          "c_tit":'花材',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
      ]
    }
  },
  {
    "title":'永生花',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'对象',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'全部',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送女友',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送男性',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送长辈',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送朋友',
            }
          ]
        },
        {
          "c_tit":'场合',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
        {
          "c_tit":'花材',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
      ]
    }
  },
  {
    "title":'蛋糕',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'品牌',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'品牌1',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'品牌2',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'品牌3',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'品牌4',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'品牌5',
            }
          ]
        }
      ]
    }
  },
  {
    "title":'特色礼品',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'对象',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'全部',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送女友鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送男性鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送长辈鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'送朋友鲜花',
            }
          ]
        },
        {
          "c_tit":'场合',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
        {
          "c_tit":'花材',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'爱情鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'生日鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'探望慰问',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'商务鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'祝福庆贺',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'婚庆鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'道歉鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'哀思鲜花',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'港澳台鲜花',
            }
          ]
        },
      ]
    }
  },
  {
    "title":'礼篮',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'礼篮',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'礼篮',
            }
          ]
        }
      ]
    }
  },
  {
    "title":'绿植花卉',
    "list":{
      "show_img":'flower.png',
      "content_list":[
        {
          "c_tit":'绿植花卉',
          "c_list":[
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'全部',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'绿色植物',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'盆栽花卉',
            },
            {
              "c_img":'m_category_hot_Lover.png',
              "c_text":'剁肉盆栽',
            }
          ]
        }
      ]
    }
  },
]
//点击首页查看更多->点击 筛选
let  checkList = [
  {
    tit:'人群',
    conlist:['送女友','送男性','送朋友','送长辈']
  },
  {
    tit:'场合',
    conlist:['爱情鲜花','生日鲜花','探病慰问','商务鲜花','祝福庆贺','婚庆鲜花','道歉鲜花','哀思鲜花']
  },
  {
    tit:'花材',
    conlist:['玫瑰','百合','康乃馨','向日葵','扶郎','绣球','郁金香','马蹄莲']
  },
  {
    tit:'类别',
    conlist:['传情花束','创意花盒','瓶插花','精致花篮','开业花篮','设计师款']
  },
  {
    tit:'颜色',
    conlist:['红色','粉色','香槟色','黄色','白色','紫色','蓝色']
  }
]
//首页轮播图照片
let swiperImg = [
  {
    id:0,
    img:'19_thanksday_m.jpg'
  },
  {
    id:1,
    img:'18_birthday_m.jpg'
  },
  {
    id:2,
    img:'19_banner_sheshou_m.jpg'
  },
  {
    id:3,
    img:'18_youflower_m.jpg'
  }

]
//首页菜单
let homeMenu= [
  {
    id:0,
    text:'鲜花',
    icon:'m_home_category_flower.png'
  },
  {
    id:1,
    text:'永生花',
    icon:'m_home_category_ppf.png'
  },
  {
    id:2,
    text:'蛋糕',
    icon:'m_home_category_cake.png'
  },
  {
    id:3,
    text:'礼品',
    icon:'m_home_category_gift.png'
  },
  {
    id:4,
    text:'巧克力',
    icon:'m_home_category_chocolate.png'
  }
]
//一秒选花
let choseFlower = [
  {
    id:0,
    
  }
]
//首页下面的数据1
let homeList =[
  {
    tit:'送恋人/爱情鲜花',
    list:[
      {
        img:'品味.jpg',
        name:'一往情深',
        text:'精品玫瑰礼盒:19枝红玫瑰，勿忘我0.1扎',
        tit:'经典爆款，年销售冠军！',
        price: 315,
        now_price: 239,
        haso:'已销售7.5万件'
      },
      {
        img:'微信图片_20200902171002.jpg',
        name:'粉雪佳人',
        text:'戴安娜粉玫瑰11枝、白色香水百合2枝、白色洋桔梗5枝',
        tit:'清新典雅，至臻设计',
        price: 282,
        now_price: 219,
        haso:'已销售1342件'
      },
      {
        img:'微信图片_202009021625154.jpg',
        name:'不变的承诺',
        text:'99枝红玫瑰',
        tit:'经典99枝，鼎力推荐！',
        price: 539,
        now_price: 766,
        haso:'已销售6.2万件'
      },
      {
        img:'m_category_hot_Lover.png',
        name:'忘情巴黎',
        text:'33枝红玫瑰',
        tit:'经典99枝，鼎力推荐！',
        price: 298,
        now_price: 382,
        haso:'已销售6.5万件'
      },
      {
        img:'微信图片_202009021625151.jpg',
        name:'一心一意',
        text:'玫瑰11枝，粉色勿忘我0.3扎',
        tit:'经典款式 精选爆款',
        price: 189,
        now_price: 139,
        haso:'已销售11.0万件'
      },
      {
        img:'微信图片_20200902162515.jpg',
        name:'甜美公主',
        text:'白玫瑰22枝，粉佳人粉玫瑰14枝，粉色桔梗5枝',
        tit:'甜美设计 清新典雅',
        price: 485,
        now_price: 368,
        haso:'已销售2.2万件'
      },
      {
        img:'微信图片_20200902162515.jpg',
        name:'用心爱你',
        text:'99枝：33枝戴安娜＋66枝红玫瑰',
        tit:'与你相守，直到天荒地老',
        price: 869,
        now_price: 520,
        haso:'已销售3.3万件'
      },
      {
        img:'m_category_hot_Lover.png',
        name:'爱在心头',
        text:'玫瑰50枝：戴安娜粉玫瑰19枝，红玫瑰31枝',
        tit:'双色搭配 赏心悦目',
        price: 479,
        now_price: 389,
        haso:'已销售1.9万件'
      }

    ]
  },
  {
    tit:'送长辈鲜花',
    list:[
      {
        img:'微信图片_202009021625154.jpg',
        name:'馨情无限',
        text:'戴安娜玫瑰11枝，红色康乃馨11支，红色石竹梅4枝',
        tit:'高端花盒设计',
        price: 312,
        now_price: 238,
        haso:'已销售6002件'
      },
      {
        img:'微信图片_202009021625154.jpg',
        name:'语笑嫣然',
        text:'粉佳人玫瑰9枝、粉色小菊、洋桔梗、尤加利叶',
        tit:'节日定制款',
        price: 256,
        now_price: 198,
        haso:'已销售1172件'
      },
      {
        img:'微信图片_20200902162515.jpg',
        name:'留住好时光',
        text:'粉绣球1枝，粉雪山玫瑰6枝',
        tit:'精选昆明A级花材',
        price: 306,
        now_price: 239,
        haso:'已销售8476件'
      },
      {
        img:'/m_category_hot_Lover.png',
        name:'星河璀璨',
        text:'香槟玫瑰9枝、蓝绣球、向日葵、白色洋桔梗、尤加利叶',
        tit:'倾情设计，为爱相守',
        price: 376,
        now_price: 289,
        haso:'已销售713件'
      },
      {
        img:'微信图片_20200902171002.jpg',
        name:'母爱',
        text:'紫红色康乃馨9枝，粉色多头康乃馨10枝',
        tit:'红粉搭配 花色明艳',
        price: 228,
        now_price: 172,
        haso:'已销售1.4万件'
      },
      {
        img:'微信图片_202009021625151.jpg',
        name:'真的爱你',
        text:'粉色康乃馨10枝，浅蓝色绣球1枝，浅紫色紫罗兰5枝',
        tit:'清新设计 多样花材',
        price: 369,
        now_price: 288,
        haso:'已销售912万件'
      },
    ]
  }
]
//首页下面的数据2
let homeListDown=[
  {
    tit:'永生花推荐',
    list:[
      {
        img:'1073257.jpg_220x240.jpg',
        des:'',
        name:'一路上有你/三色玫瑰',
        text:'一路上有你/三色玫瑰·5年不凋谢，真空保鲜花，彩玫系列，玫瑰5枝',
        price: 569,
        now_price: 359,
        haso:'已销售1937件'
      },
      {
        img:'1073263.jpg_220x240.jpg',
        des:'畅销',
        name:'我如此爱你-口红款999',
        text:'我如此爱你-口红款999·专柜正品Dior#999口红＋进口永生玫瑰礼盒',
        price: 788,
        now_price: 588,
        haso:'已销售6322件'
      },
      {
        img:'1073185.jpg_220x240.jpg',
        des:'独创设计',
        name:'守护初心口红款礼盒/炽热红',
        text:'守护初心口红款礼盒/炽热红·迪奥口红两支：Dior#520、Dior#999口红(专柜正品)＋进口永生玫瑰礼盒',
        price: 1099,
        now_price: 999,
        haso:'已销售89件'
      },
      {
        img:'1060038.jpg_220x240.jpg',
        des:'创意新品',
        name:'永生花满月艺术台灯/朦胧粉',
        text:'永生花满月艺术台灯/朦胧粉·永生花台灯',
        price: 498,
        now_price: 398,
        haso:'已销售60件'
      }
    ]
  },
  {
    tit:'蛋糕推荐',
    list:[
      {
        img:'5602016.jpg_220x240.jpg',
        des:'生日推荐',
        name:'四重奏蛋糕(约2磅)',
        text:'四重奏蛋糕(约2磅)·方形/巧克力/榴莲/慕斯蛋糕',
        price: 296,
        now_price: 228,
        haso:'已销售2676件'
      },
      {
        img:'9092114.jpg_220x240.jpg',
        des:'',
        name:'真爱+ 生日蛋糕B款（8寸）',
        text:'真爱+ 生日蛋糕B款（8寸）·红玫瑰9枝，石竹梅4枝，栀子叶0.5扎',
        price: 298,
        now_price: 268,
        haso:'已销售1080件'
      },
      {
        img:'5010041.jpg_220x240.jpg',
        des:'',
        name:'陪伴左右',
        text:'陪伴左右·2磅(8寸)水果蛋糕',
        price: 198,
        now_price: 168,
        haso:'已销售5346件'
      },
      {
        img:'5302008.jpg_220x240.jpg',
        des:'',
        name:'蝶恋花景(8寸)',
        text:'蝶恋花景(8寸)·元祖鲜奶蛋糕，布丁加水果夹层',
        price: 358,
        now_price: 258,
        haso:'已销售60件'
      }
    ]
  },
  {
    tit:'礼品推荐',
    list:[
      {
        img:'1076078.jpg_220x240.jpg',
        des:'限量版首发',
        name:'Dior烈艳蓝金唇膏烟花限量版套装',
        text:'Dior烈艳蓝金唇膏烟花限量版套装·高订套装饰以璀璨烟花，一套汇集6款明星色号，打造百变妆容 演绎百变魅力',
        price: 1580,
        now_price: 1680,
        haso:'已销售76件'
      },
      {
        img:'1076080.jpg_220x240.jpg',
        des:'新品特惠',
        name:'施华洛世奇跳动的心项链/镀玫瑰金色',
        text:'施华洛世奇跳动的心项链/镀玫瑰金色·SPARKLING DC系列新品项链，专柜正品，全国联保',
        price: 1290,
        now_price: 968,
        haso:'已销售59件'
      },
      {
        img:'1076062.jpg_220x240.jpg',
        des:'新品特惠',
        name:'星期耳钉礼盒',
        text:'星期耳钉礼盒·s925银个性耳钉',
        price: 298,
        now_price: 198,
        haso:'已销售1167件'
      },
      {
        img:'1077011.jpg_220x240.jpg',
        des:'精选礼品',
        name:'woody书灯木质led折叠usb书本灯-时尚版（黑胡桃',
        text:'woody书灯木质led折叠usb书本灯-时尚版（黑胡桃）·',
        price: 298,
        now_price: 198,
        haso:'已销售189件'
        
      }
    ]
  },
  {
    tit:'巧克力推荐',
    list:[
      {
        img:'1207068.jpg_220x240.jpg',
        des:'限量版首发',
        name:'心动炫彩口红礼盒',
        text:'心动炫彩口红礼盒·夹心巧克力',
        price: 258,
        now_price: 258,
        haso:'已销售1870件'
      },
      {
        img:'1205050.jpg_220x240.jpg',
        des:'限量版首发',
        name:'手工松露巧克力酒味夹心爱心礼盒13粒',
        text:'手工松露巧克力酒味夹心爱心礼盒13粒·酒味夹心巧克力',
        price: 358,
        now_price: 258,
        haso:'已销售1477件'
      },
      {
        img:'1207010.jpg_220x240.jpg',
        des:'限量版首发',
        name:'巧克巧蔻定制16粒装手工夹心巧克力',
        text:'巧克巧蔻定制16粒装手工夹心巧克力·手工夹心巧克力',
        price: 388,
        now_price: 288,
        haso:'已销售4437件'
      },
      {
        img:'1204042.jpg_220x240.jpg',
        des:'限量版首发',
        name:'Felchlin妃亭18粒装巧克力礼',
        text:'Felchlin妃亭18粒装巧克力礼盒·德国进口松露夹心巧克力',
        price: 348,
        now_price: 348,
        haso:'已销售303件'
      }
    ]
  }
]




Mock.mock('http://127.0.0.1:3001/data','post',function(){
  return{
    classify,homeListDown,homeMenu
  }
})