// Mock.mock('url', 'method', fn(){})
let classify = [
    {
      "title":'热门推荐',
      "list":{
        //顶部图片
        "show_img":'hot.png',
        //下面的内容
        "content_list":[
          {
            "c_img":'m_category_hot_Lover.png',
            "c_text":'送恋人鲜花',
          },
          {
            "c_img":'m_category_hot_Elder.png',
            "c_text":'送长辈鲜花',
          },
          {
            "c_img":'m_category_hot_Birthday.png',
            "c_text":'生日鲜花',
          },
          {
            "c_img":'m_category_hot_Boxedflowers.png',
            "c_text":'礼盒鲜花',
          },
          {
            "c_img":'m_category_ppf_sort_Box.png',
            "c_text":'永生花',
          },
          {
            "c_img":'m_category_hot_Cake.png',
            "c_text":'蛋糕',
          },
          {
            "c_img":'m_category_hot_Cake_ganso.png',
            "c_text":'元祖蛋糕',
          },
          {
            "c_img":'m_category_hot_Goldfoilflower.png',
            "c_text":'金箔花',
          },
          {
            "c_img":'m_category_hot_Jewelry.png',
            "c_text":'首饰',
          },
          {
            "c_img":'m_category_hot_Chocolate_qiaoluo.png',
            "c_text":'巧罗巧克力',
          },
          {
            "c_img":'m_category_hot_CreativeGifts.png',
            "c_text":'创意礼品',
          },
          {
            "c_img":'m_category_hot_Groupbuy.png',
            "c_text":'企业团购',
          }
        ]
      }
    },
    {
      "title":'鲜花',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'对象',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'全部',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送女友鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送男性鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送长辈鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送朋友鲜花',
              }
            ]
          },
          {
            "c_tit":'场合',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
          {
            "c_tit":'花材',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
        ]
      }
    },
    {
      "title":'永生花',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'对象',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'全部',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送女友',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送男性',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送长辈',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送朋友',
              }
            ]
          },
          {
            "c_tit":'场合',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
          {
            "c_tit":'花材',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
        ]
      }
    },
    {
      "title":'蛋糕',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'品牌',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'品牌1',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'品牌2',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'品牌3',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'品牌4',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'品牌5',
              }
            ]
          }
        ]
      }
    },
    {
      "title":'特色礼品',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'对象',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'全部',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送女友鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送男性鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送长辈鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'送朋友鲜花',
              }
            ]
          },
          {
            "c_tit":'场合',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
          {
            "c_tit":'花材',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'爱情鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'生日鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'探望慰问',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'商务鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'祝福庆贺',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'婚庆鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'道歉鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'哀思鲜花',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'港澳台鲜花',
              }
            ]
          },
        ]
      }
    },
    {
      "title":'礼篮',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'礼篮',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'礼篮',
              }
            ]
          }
        ]
      }
    },
    {
      "title":'绿植花卉',
      "list":{
        "show_img":'flower.png',
        "content_list":[
          {
            "c_tit":'绿植花卉',
            "c_list":[
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'全部',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'绿色植物',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'盆栽花卉',
              },
              {
                "c_img":'m_category_hot_Lover.png',
                "c_text":'剁肉盆栽',
              }
            ]
          }
        ]
      }
    },
  ]
Mock.mock('http://127.0.0.1:3001/data','post', function(){
    return classify;
})